# Generated by Django 3.0 on 2020-10-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.SmallIntegerField(choices=[(0, 'PC服务器'), (1, '刀片机'), (2, '小型机')], default=0, verbose_name='服务器类型')),
                ('created_by', models.CharField(choices=[('auto', '自动添加'), ('manual', '手工录入')], default='auto', max_length=32, verbose_name='添加方式')),
                ('IP', models.CharField(default='', max_length=30, verbose_name='IP地址')),
                ('MAC', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Mac地址')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务器型号')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='主机名')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统类型')),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name='发行商')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='资产标识')),
            ],
            options={
                'verbose_name': '服务器管理',
                'verbose_name_plural': '服务器管理',
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='root', max_length=30, verbose_name='用户名')),
                ('password', models.CharField(default='123', max_length=40, verbose_name='密码')),
                ('pkey', models.CharField(default='id_rsa', max_length=40, verbose_name='私钥')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanhost.Server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '服务器用户管理',
                'verbose_name_plural': '服务器用户管理',
                'db_table': 'users',
            },
        ),
    ]
